const initialstate = {
  data: [
    {
      img: "doctor-thumb-01.jpg",
      name: "Dr. Ruby Perrin",
      detail: "MDS - Periodontology and Oral Implantology, BDS",
      speciality: " Cardiologists",
      star: "(17)",
      loc: "Florida, USA",
      img1: "specialities-05.png",
      link1: "feature-01.jpg",
      link2: "feature-02.jpg",
      link3: "feature-03.jpg",
      link4: "feature-04.jpg",
      cardio: "Cardiologist Fillings",
      white: "Whitneing",
      percent: "94%",
      feedback: "17 Feedback",
      location: "Florida, USA",
      fee: "$300 - $1000",
    },
    {
      img: "doctor-thumb-01.jpg",
      name: "Dr. Ruby Perrin",
      detail: "MDS - Periodontology and Oral Implantology, BDS",
      speciality: " Cardiologists",
      star: "(17)",
      loc: "Florida, USA",
      img1: "specialities-05.png",
      link1: "feature-01.jpg",
      link2: "feature-02.jpg",
      link3: "feature-03.jpg",
      link4: "feature-04.jpg",
      cardio: "Cardiologist Fillings",
      white: "Whitneing",
      percent: "90%",
      feedback: "17 Feedback",
      location: "Florida, USA",
      fee: "$300 - $1000",
    },
    {
      img: "doctor-thumb-01.jpg",
      name: "Dr. Ruby Perrin",
      detail: "MDS - Periodontology and Oral Implantology, BDS",
      speciality: " Cardiologists",
      star: "(17)",
      loc: "Florida, USA",
      img1: "specialities-05.png",
      link1: "feature-01.jpg",
      link2: "feature-02.jpg",
      link3: "feature-03.jpg",
      link4: "feature-04.jpg",
      cardio: "Cardiologist Fillings",
      white: "Whitneing",
      percent: "98%",
      feedback: "17 Feedback",
      location: "Florida, USA",
      fee: "$300 - $1000",
    },
    {
      img: "doctor-thumb-01.jpg",
      name: "Dr. Ruby Perrin",
      detail: "MDS - Periodontology and Oral Implantology, BDS",
      speciality: " Cardiologists",
      star: "(17)",
      loc: "Florida, USA",
      img1: "specialities-05.png",
      link1: "feature-01.jpg",
      link2: "feature-02.jpg",
      link3: "feature-03.jpg",
      link4: "feature-04.jpg",
      cardio: "Cardiologist Fillings",
      white: "Whitneing",
      percent: "98%",
      feedback: "17 Feedback",
      location: "Florida, USA",
      fee: "$300 - $1000",
    },
    {
      img: "doctor-thumb-01.jpg",
      name: "Dr. Ruby Perrin",
      detail: "MDS - Periodontology and Oral Implantology, BDS",
      speciality: " Cardiologists",
      star: "(17)",
      loc: "Florida, USA",
      img1: "specialities-05.png",
      link1: "feature-01.jpg",
      link2: "feature-02.jpg",
      link3: "feature-03.jpg",
      link4: "feature-04.jpg",
      cardio: "Cardiologist Fillings",
      white: "Whitneing",
      percent: "98%",
      feedback: "17 Feedback",
      location: "Florida, USA",
      fee: "$300 - $1000",
    },
    {
      img: "doctor-thumb-01.jpg",
      name: "Dr. Ruby Perrin",
      detail: "MDS - Periodontology and Oral Implantology, BDS",
      speciality: " Cardiologists",
      star: "(17)",
      loc: "Florida, USA",
      img1: "specialities-05.png",
      link1: "feature-01.jpg",
      link2: "feature-02.jpg",
      link3: "feature-03.jpg",
      link4: "feature-04.jpg",
      cardio: "Cardiologist Fillings",
      white: "Whitneing",
      percent: "60%",
      feedback: "17 Feedback",
      location: "Florida, USA",
      fee: "$300 - $1000",
    },
  ],
};

const maplist = (state = initialstate, action) => {
  switch (action.type) {
    case "MAPLIST":
      return {
        ...state,
        maplist: state.maplist,
      };
    default:
      return state;
  }
};
export default maplist;
